Update to n 8.0.2

diff --git a/n b/n
--- a/n
+++ b/n
@@ -61,7 +61,7 @@ function n_grep() {
 # Setup and state
 #
 
-VERSION="v8.0.0"
+VERSION="v8.0.2"
 
 N_PREFIX="${N_PREFIX-/usr/local}"
 N_PREFIX=${N_PREFIX%/}
@@ -337,7 +337,7 @@ enter_fullscreen() {
 leave_fullscreen() {
   # Set cursor to normal
   tput cnorm 2> /dev/null
-  # Restore screen contentsq
+  # Restore screen contents
   tput rmcup 2> /dev/null
   stty echo
 }
@@ -740,8 +740,7 @@ activate() {
       printf '\nNote: the node command changed location and the old location may be remembered in your current shell.\n'
       log old "${original_node}"
       log new "${active_node}"
-      # shellcheck disable=SC2016
-      printf 'To reset the command location hash either start a new shell, or execute PATH="$PATH"\n'
+      printf 'If "node --version" shows the old version then start a new shell, or reset the location hash with:\nhash -r  (for bash, zsh, ash, dash, and ksh)\nrehash   (for csh and tcsh)\n'
     fi
   fi
 }
@@ -762,6 +761,7 @@ install() {
 
   local dir="${CACHE_DIR}/${g_mirror_folder_name}/${version}"
 
+  # Note: decompression flags ignored with default Darwin tar which autodetects.
   if test "$N_USE_XZ" = "true"; then
     local tarflag="-Jx"
   else
@@ -789,9 +789,13 @@ install() {
   cd "${dir}" || abort "Failed to cd to ${dir}"
 
   log fetch "$url"
-  do_get "${url}" | tar "$tarflag" --strip-components=1 --no-same-owner
-  if [[ "${PIPESTATUS[0]}" -ne 0 ]]; then
+  do_get "${url}" | tar "$tarflag" --strip-components=1 --no-same-owner -f -
+  pipe_results=( "${PIPESTATUS[@]}" )
+  if [[ "${pipe_results[0]}" -ne 0 ]]; then
     abort "failed to download archive for $version"
+  fi
+  if [[ "${pipe_results[1]}" -ne 0 ]]; then
+    abort "failed to extract archive for $version"
   fi
   [ "$GET_SHOWS_PROGRESS" = "true" ] && erase_line
   rm -f "$dir/n.lock"
@@ -1269,7 +1273,7 @@ function display_remote_versions() {
   elif is_download_folder "${version}"; then
     match='.'
   elif is_download_version "${version}"; then
-    version="${version#${g_mirror_folder_name}/}"
+    version="${version#"${g_mirror_folder_name}"/}"
     if [[ "${version}" = "latest" || "${version}" = "current" ]]; then
       match_count=1
       match='.'
